FROM registry.cn-shanghai.aliyuncs.com/odboy/ops:runtime-jdk11

# 需传入应用名称
ARG APP_NAME=kenaito-aops
ARG APP_ENV=dev

# 以下内容不要改
ENV APP_NAME=$APP_NAME
ENV APP_ENV=$APP_ENV
VOLUME /usr/local/apps/${APP_NAME}/logs
ADD ${APP_NAME}.tar.gz /usr/local/apps/${APP_NAME}/
WORKDIR /usr/local/apps/${APP_NAME}
CMD java -Djava.security.egd=file:/dev/./urandom -jar ${APP_NAME}.jar --spring.profiles.active=${APP_ENV}
